name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: [12, 14]
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
        
    - run: yarn install --frozen-lockfile

    - run: yarn tsc
    
    - run: yarn lint
      
    - run: yarn test
